myapp/urls.py
from django.urls import path, include
from .views.edit_profile import EditProfileView
from .views.edit_student_profile import EditStudentProfileView, user_university, user_major
from .apis.university import MajorAPIView

app_name = "myapp"
urlpatterns = [
    path("edit_profile", EditProfileView.as_view(), name="edit_profile"),
    path("edit_student_profile", EditStudentProfileView.as_view(), name="edit_student_profile"),
    path('user_university/',user_university,name='user_university'),
    #path('user_major/<int:university_id>',user_major,name='user_major'),
    #path('myapp/user_major/(?P<university_id>[0-9]+)$',user_major,name='user_major'),
    path('api/major', MajorAPIView.as_view(), name='major_api')
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from mysite.views import IndexView, LoginRequiredView
import debug_toolbar


urlpatterns = [
    path('', include('allauth.urls')),
    path('', IndexView.as_view(), name="index"),
    path('login_required', LoginRequiredView.as_view(), name="login_required"),
    path('admin/', admin.site.urls),
    path('myapp/', include('myapp.urls')),
    path('editlecture/', include('editlecture.urls')),
]

if settings.DEBUG:
    urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]

myapp/models.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin, UserManager
from django.contrib.auth.validators import UnicodeUsernameValidator
from django.db.models.fields import BLANK_CHOICE_DASH
from django.utils.translation import gettext_lazy as _
from django.utils import timezone
from django.core.mail import send_mail
import ulid

from mysite.const import USER_TYPE

# class PermissionType(models.IntegerChoices):
#     STUDENT = (0,'生徒')
#     MANAGER = (1,'大学職員')


class CustomUserManager(UserManager):
    '''
    Userを作成するための処理
    Userの項目が変更になっているので、こちらも変更の必要がある
    '''    
    
    def _create_user(self, email, password, **extra_fields):
        """
        Create and save a user with the given username, email, and password.
        """
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user
    
    
    def create_user(self, email=None, password=None,user_type=None, **extra_fields):
        '''
        一般ユーザーを作成する処理
        '''
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(email, password,user_type,**extra_fields)
    
    
    def create_superuser(self, email=None, password=None, **extra_fields):
        '''
        管理者ユーザーを作成する処理
        '''
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self._create_user(email, password, **extra_fields)
    
class StudentUser(models.Model):
    id = models.CharField(max_length=32, default=ulid.new, primary_key=True, editable=False)
    # username = models.CharField(max_length=150,unique=True)
    # permission_type = models.IntegerField(choices=PermissionType.choices,default=PermissionType.STUDENT)
    nickname = models.CharField(_('ニックネーム'), max_length=32, blank=True)
    university_name = models.ForeignKey('University',on_delete=models.CASCADE,null=True,blank=True)
    major_name = models.ForeignKey('Major',on_delete=models.CASCADE,null=True,blank=True)
    
    def __str__(self):
        return self.nickname
    
    class Meta:
        verbose_name = "学生ユーザー"
        verbose_name_plural = "学生ユーザー"
        db_table = "student_user"
        
class EditUser(models.Model):
    id = models.CharField(max_length=32, default=ulid.new, primary_key=True, editable=False) 
    nickname = models.CharField(_('ニックネーム'), max_length=32, blank=True)
    # username = models.CharField(max_length=150,unique=True)
    university_name = models.ForeignKey('University',on_delete=models.CASCADE,null=True,blank=True)
    
    def __str__(self):
        return self.nickname
    
    class Meta:
        verbose_name = "editユーザー"
        verbose_name_plural = "editユーザー"
        db_table = "edit_user"
        
class User(AbstractBaseUser, PermissionsMixin):
    id = models.CharField(max_length=32, default=ulid.new, primary_key=True, editable=False)
    email = models.EmailField(_('メールアドレス'), blank=False, unique=True, db_index=True) 
    username = models.CharField(_('ユーザーネーム'), max_length=150, blank=True)
    user_type = models.IntegerField(_('ユーザータイプ'), blank=False,default=0)
    student_user = models.ForeignKey(StudentUser,db_column="student_user_id",blank=True, db_index=True, default=None, null=True, on_delete=models.SET_NULL)
    edit_user = models.ForeignKey(EditUser,db_column="edit_user_id", blank=True, db_index=True, default=None, null=True, on_delete=models.SET_NULL)
    date_joined = models.DateTimeField(_('date joined'), default=timezone.now)
    is_staff = models.BooleanField(
        _('staff status'),
        default=False,
        help_text=_(
            'Designates whether the user can log into this admin site.'),
    )
    is_active = models.BooleanField(
        _('active'),
        default=True,
        help_text=_(
            'Designates whether this user should be treated as active. '
            'Unselect this instead of deleting accounts.'
        ),
    )
    
    objects = CustomUserManager()
    # emailの項目名を指定
    EMAIL_FIELD = 'email'
    # ログイン時にIDになる項目名を指定
    USERNAME_FIELD = 'email'
    # 必須入力とする項目名(USERNAME_FIELDに指定した項目は必ず指定する前提のため指定しない)
    REQUIRED_FIELDS = []
    
    class Meta:
        verbose_name = _('ログイン用共通ユーザー')
        verbose_name_plural = _('ログイン用共通ユーザー')
        db_table = "auth_user"
        
    def clean(self):
        super().clean()
        self.email = self.__class__.objects.normalize_email(self.email)

    def email_user(self, subject, message, from_email=None, **kwargs):
        """Send an email to this user."""
        send_mail(subject, message, from_email, [self.email], **kwargs)
        
    def is_student_user(self):
        return self.user_type == USER_TYPE.STUDENT_USER
    
    def is_edit_user(self):
        return self.user_type == USER_TYPE.EDIT_USER


class University(models.Model):
    university_name = models.CharField(max_length=30,null=True,blank=True)

    def __str__(self):
        return self.university_name

class Major(models.Model):
    major_name = models.CharField(max_length=30)
    r_university = models.ForeignKey('University', on_delete=models.CASCADE,null=True,blank=True)

    def __str__(self):
        return self.major_name

myapp/forms/edit_user.py
from django.forms import ModelForm, ChoiceField, CharField, Textarea
from myapp.models import EditUser

class EditUserForm(ModelForm):
    class Meta:
        model = EditUser
        fields = ("nickname",)

myapp/forms/student_user.py
from django.forms import ModelForm, ChoiceField, CharField, Textarea
from myapp.models import StudentUser

class StudentUserForm(ModelForm):
    
    class Meta:
        model = StudentUser
        fields = ("nickname", "university_name", "major_name")

myapp/views/edit_profile.py
from django.shortcuts import render, redirect
from django.http.response import HttpResponse
from django.views.generic import TemplateView
from django.http import Http404
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator

from ..forms.edit_user import EditUserForm
from mysite.const import USER_TYPE

app_name = "myapp"

@method_decorator(login_required, name="dispatch")
class EditProfileView(TemplateView):
    template_name = f"{app_name}/edit_profile.html"
    
    def get(self, request):
        if not request.user.user_type == USER_TYPE.EDIT_USER:
            return Http404("生徒アカウントは、このページは表示できません")
        form = EditUserForm(instance=request.user.edit_user)
        return self.render_to_response({"form": form})
    
    
    def post(self, request):
        if not request.user.user_type == USER_TYPE.EDIT_USER:
            return Http404("生徒アカウントは、このページは表示できません")
        form = EditUserForm(request.POST, instance=request.user.edit_user)
        if not form.is_valid():
            messages.error(request, "保存に失敗しました")
            for field in form:
                for error in field.errors:
                    messages.error(request, f"{field.label}: {error}")
        else:
            form.save()
            messages.success(request, "保存しました")
            
        return self.render_to_response({"form": form})

myapp/views/edit_student_profile.py
from django.shortcuts import render, redirect
from django.http.response import HttpResponse
from django.views.generic import TemplateView
from django.http import Http404
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from ..models import University,Major,StudentUser
from ..forms.student_user import StudentUserForm
from mysite.const import USER_TYPE

app_name = "myapp"

@method_decorator(login_required, name="dispatch")
class EditStudentProfileView(TemplateView):
    template_name = f"{app_name}/edit_student_profile.html"
    
    def get(self,request):
        if not request.user.user_type == USER_TYPE.STUDENT_USER:
            raise Http404('職員アカウントは、このページは表示できません')
        print(request.user.student_user)
        form = StudentUserForm(instance=request.user.student_user)
        return self.render_to_response({"form":form})
    
    def post(self,request):
        if not request.user.user_type == USER_TYPE.STUDENT_USER:
            raise Http404("職員アカウントは、このページは表示できません")
        form = StudentUserForm(request.POST, instance=request.user.student_user)
        if not form.is_valid():
            messages.error(request, "保存に失敗しました")
            for field in form:
                for error in field.errors:
                    messages.error(request, f"{field.label}: {error}")
        else:
            form.save()
            #a,b = user_university()
            a,b = user_university(request)
            print(a)
            print(b)
            student = request.user.student_user
            student.university_name = a
            student.major_name = b
            student.save()
            messages.success(request, "保存しました")
            
        return self.render_to_response({"form": form})

def user_university(request):
    universitys = University.objects.all()
    if request.method == "POST":
        university_id = request.POST.get('university_id')
        return redirect('myapp/user_major/university_id')
    return render(request,'user_university.html',context={'universitys':universitys})
        
def user_major(request,university_id):
    major_objects = Major.objects.filter(r_university__id=university_id)
    if request.method == 'POST':
        major_id = request.POST.get('major_id')
        return university_id,major_id
    return render(request,'user_major.html',context={'major_objects':major_objects})

templates/myapp/edit_profile.html
{% extends 'base.html' %}
{% load widget_tweaks %}

{% block header %}
    <h1>職員用のプロフィール編集画面</h1>
{% endblock %}

{% block contents %}
    {% include 'message.html' %}
    <form name="main_form" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <div>
            {{ form.university_name | attr:"placeholder:大学を選択" | add_class:"any_class_name" }}
        </div>
        <button type="submit" name="save" class="any_class_name">
            保存する
        </button>
    </form>
{% endblock %}

templates/myapp/edit_student_profile.html
{% extends 'base.html' %}
{% load widget_tweaks %}

{% block header %}
    <h1>学生用のプロフィール編集画面</h1>
{% endblock %}

{% block contents %}
    {% include 'message.html' %}
    <form name="main_form" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <div>
            {{ form.nickname | attr:"placeholder:ニックネームを入力" | add_class:"any_class_name" }}
        </div>
        <div>
            {{ form.university_name | attr:"placeholder:大学を選択" | add_class:"any_class_name" }}
        </div>
        <div>
            {{ form.major_name | attr:"placeholder:学部を選択" | add_class:"any_class_name" }}
        </div>
        <button type="submit" name="save" class="any_class_name">
            保存する
        </button>
    </form>
{% endblock %}

{% block scripts %}
    <script>
        const CSRF_TOKEN = '{{ csrf_token }}'
        const majorNameElm = document.getElementById("id_major_name")
        document.getElementById("id_university_name").addEventListener("input", async (e)=>{
            const res = await fetchMajors(e.target.value)
            const majors = await res.json()
            console.log(majors)
            generateMajorSelection(majors, majorNameElm)
        })
        async function fetchMajors(universityId){
            res = await executeAPI("{% url 'myapp:major_api' %}" + "?university_id=" + universityId, null, "GET")
            return await res
        }

        async function executeAPI(url, body, method) {
            console.log(url)
            try {
                const headers = {
                    'content-type': 'application/json',
                    'X-CSRFToken': CSRF_TOKEN
                }
                const res = await fetch(
                    url, 
                    {
                        method: method,
                        headers: headers,
                        body: body
                    }
                )
                if (res.status >= 200 && res.status < 300) {
                    return await res;
                }
                else {
                    alert("APIエラー")
                    console.log(res)
                    return null;
                }
            } catch (e) {
                console.log(e);
                return null;
            }
        }

        async function removeAllSelectOptions(elm){
            let options = await elm.getElementsByTagName("option");
            for(let i = options.length-1; i >= 0; i-- ) {
                elm.removeChild( options.item( i ) );
            }
        } 

        async function generateMajorSelection(majors, selectionElm){
            await removeAllSelectOptions(selectionElm);
            let option = document.createElement('option');
            for(let major of majors){
                let option = document.createElement('option');
                option.innerHTML = major.major_name;
                option.value = major.id;
                selectionElm.appendChild(option);
                
            }
        }
    </script>
{% endblock %}