myapp/urls.py
from django.urls import path, include
from .views.edit_profile import EditProfileView
from .views.edit_student_profile import EditStudentProfileView, user_university, user_major
from .apis.university import MajorAPIView

app_name = "myapp"
urlpatterns = [
    path("edit_profile", EditProfileView.as_view(), name="edit_profile"),
    path("edit_student_profile", EditStudentProfileView.as_view(), name="edit_student_profile"),
    path('user_university/',user_university,name='user_university'),
    #path('user_major/<int:university_id>',user_major,name='user_major'),
    #path('myapp/user_major/(?P<university_id>[0-9]+)$',user_major,name='user_major'),
    path('api/major', MajorAPIView.as_view(), name='major_api')
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from mysite.views import IndexView, LoginRequiredView
import debug_toolbar


urlpatterns = [
    path('', include('allauth.urls')),
    path('', IndexView.as_view(), name="index"),
    path('login_required', LoginRequiredView.as_view(), name="login_required"),
    path('admin/', admin.site.urls),
    path('myapp/', include('myapp.urls')),
    path('editlecture/', include('editlecture.urls')),
]

if settings.DEBUG:
    urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]

templates/base.html
<!-- ベースになるテンプレート -->
<html>
<head>
    <!-- タイトル -->
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    <div>
        <!-- ナビゲーションバー -->
        {% include 'navigation.html' %}
        
        <!-- コンテンツヘッダー -->
        <header>
            {% block header %}{% endblock %}
        </header>

        <!-- コンテンツ -->
        <main>
            {% block contents %}{% endblock %}
        </main>

        <!-- フッター -->
        <footer>
            {% block footer %}{% endblock %}
        </footer>
    </div>

    <!-- カスタムスクリプト -->
    {% block scripts %}{% endblock %}
</body>
</html>

templates/index.html
<html>
<head>
</head>
<body>
    <p>トップページ</p>
    <a href="{% url 'account_login' %}">ログイン</a>
    <a href="{% url 'account_signup' %}">studentユーザー会員登録</a>
    <a href="{% url 'account_signup' %}?user_type=1">editユーザー会員登録</a>
</body>
</html>

templates/login_required.html
<html>
<head>
</head>
<body>
    <p>ログインが必要なページです。ログインしてください。</p>
    <a href="{% url 'myapp:login' %}auth0">ログイン</a>
</body>
</html>

templates/message.html
<!-- メッセージ表示 -->
{% if messages %}
<div class="mb-2">
    {% for message in messages %}
        {% if message.tags == "error" %}
        <div id="message{{ forloop.counter }}" class="flex justify-center items-center font-medium py-4 px-2 bg-white rounded-md text-red-700 bg-red-100 border border-red-300">
            <div class="text-xl font-normal  max-w-full flex-initial">
                {{ message }}
            </div>
        </div>
        {% endif %}
        {% if message.tags == "info" %}
        <div id="message{{ forloop.counter }}" class="flex justify-center items-center font-medium py-4 px-2 bg-white rounded-md text-yellow-700 bg-yellow-100 border border-yellow-300">
            <div class="text-xl font-normal  max-w-full flex-initial">
                <div class="py-2">
                    {{ message }}
                </div>
            </div>
        </div>
        {% endif %}
        {% if message.tags == "success" %}
        <div id="message{{ forloop.counter }}" class="flex justify-center items-center font-medium py-4 px-2 bg-white rounded-md text-green-700 bg-green-100 border border-green-300 ">
            <div class="text-xl font-normal  max-w-full flex-initial">
                {{ message }}
            </div>
        </div>
        {% endif %}
    {% endfor %}
</div>
{% endif %}

templates/navigation.html
<div>
    <!-- ログイン有無、企業・一般ユーザーの状態によって表示を切り替え -->
    {% comment %} <a href="{% url 'recruit:item' %}">求人一覧</a> {% endcomment %}
    {% if request.user.is_authenticated %}
        {% if request.user.is_student_user %}
            <a href="{% url 'myapp:edit_student_profile' %}">プロフィール編集</a>
        {% elif request.user.is_edit_user %}
            <a href="{% url 'myapp:edit_profile' %}">プロフィール編集</a>
        {% endif %}
    {% endif %}
    {% if request.user.is_authenticated %}
        <a href="{% url 'account_logout' %}">ログアウト</a>
    {% else %}
        <a href="{% url 'account_login' %}">ログイン</a>
    {% endif %}
    {% if request.user.is_authenticated %}
        <p>[ログイン中です] email: {{ user.email }}</p>
    {% else %}
        <p>ログインしていません</p>
    {% endif %}
</div>

templates/user_major.html
{% extends 'base.html' %}
{% load static %}

{% block customcss %}
<link rel="stylesheet" href="{% static 'style.css' %}">
{% endblock customcss %}

{% block content %}
<form method="POST">{% csrf_token %}
    <select name="major_id">
    <option></option>
    {% for major in major_objects %}
        <option value="{{ major.id }}">{{ major.major_name }}</option>
    {% endfor %}
    </select>
    <input type="submit" value="登録する">
</form>
{% endblock content %}

templates/user_university.html
{% extends 'base.html' %}
{% load static %}

{% block customcss %}
<link rel="stylesheet" href="{% static 'style.css' %}">
{% endblock customcss %}

{% block content %}
<form method="POST">{% csrf_token %}
    <select name="university_id">
    <option></option>
    {% for university in universitys %}
        <option value="{{ university.id }}">{{ university.university_name }}</option>
    {% endfor %}
    </select>
    <input type="submit" value="登録する">
</form>
{% endblock content %}